export const UPDATE_STATE = 'UPDATE_STATE';
export const UPDATE_PLAYER_NAME = 'UPDATE_PLAYER_NAME';
export const UPDATE_CURRENT_STATE = 'UPDATE_CURRENT_STATE';
export const SWAP_CURRENT_SIDE = 'SWAP_CURRENT_SIDE';