export const STEP_CHOOSE_PLAYER = 'STEP_CHOOSE_PLAYER';
export const STEP_CHOOSE_SIDE = 'STEP_CHOOSE_SIDE';
export const STEP_PLAY_GAME = 'STEP_PLAY_GAME';
export const STEP_SHOW_RESULTS = 'STEP_SHOW_RESULTS';